[package]
name = "runpy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustpython = "0.3.1"
rustpython-vm = "0.3.1"
